### ISSUE TITLE
[Feature] 프로필 스크린 및 기능 구현

### ISSUE THREAD

**Issue by ohjooyeong** [Singrum-org/singrum-mobile#1]
## Description
프로필 스크린에 해당하는 기능들을 구현한다.
API 연동, storage 연동 시 끝났다고 판단하기로 함.

## To-Do

- [ ] 프로필 카드 - 로그인 시
  - [x] 프로필 이미지(view)
  - [x] 프로필 이름, 이메일(view)
  - [ ] 프로필 변경(func)
- [ ] 프로필 카드 - 비로그인 시
  - [x] empty 이미지
  - [x] 클릭 시 로그인, 회원가입 스크린 라우팅
- [ ] 프로필 세팅 리스트 - 공통
  - [ ] 다크모드
  - [ ] 언어
- [ ] 프로필 세팅 리스트 - 로그인 시
  - [ ] 회원탈퇴
  - [ ] 프로필 변경(임시)
- [x] 프로필 세팅 리스트 - 비 로그인 시
  - [x] 로그인, 회원가입 스크린 라우팅
