### ISSUE TITLE
[Feature] 메인 스크린 및 기능 구현

### ISSUE THREAD

**Issue by JiaLee0707** [Singrum-org/singrum-mobile#4]
## Description
메인 스크린에 해당하는 기능 구현

## To-Do
- [ ] 상단바(Header)
  - [ ] 다크모드
  - [ ] 프로필(설정) 클릭 시 프로필 스크린 라우팅
- [ ] 배너
  - [ ] 자동 슬라이드
  - [ ] 게시물이면 클릭 시 특정 스크린 라우팅(공지, 식물 카드)
- [ ] 카드 리스트
  - [ ] 최신, 인기
  - [ ] 클릭 시 세부 정보 스크린으로 라우팅
